// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'placeholder',
    appId: '1:placeholder:web:placeholder',
    messagingSenderId: 'placeholder',
    projectId: 'licenta-df25e',
    authDomain: 'licenta-df25e.firebaseapp.com',
    databaseURL: 'https://licenta-df25e-default-rtdb.firebaseio.com',
    storageBucket: 'licenta-df25e.firebasestorage.app',
    measurementId: 'G-placeholder',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'placeholder',
    appId: '1:placeholder:android:placeholder',
    messagingSenderId: '132434659741',
    projectId: 'licenta-df25e',
    databaseURL: 'https://licenta-df25e-default-rtdb.firebaseio.com',
    storageBucket: 'licenta-df25e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'placeholder',
    appId: '1:placeholder:ios:placeholder',
    messagingSenderId: 'placeholder',
    projectId: 'licenta-df25e',
    databaseURL: 'https://licenta-df25e-default-rtdb.firebaseio.com',
    storageBucket: 'licenta-df25e.firebasestorage.app',
    iosClientId: '132434659741-placeholder.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'placeholder',
    appId: '1:placeholder:ios:placeholder',
    messagingSenderId: 'placeholder',
    projectId: 'licenta-df25e',
    databaseURL: 'https://licenta-df25e-default-rtdb.firebaseio.com',
    storageBucket: 'licenta-df25e.firebasestorage.app',
    iosClientId: 'placeholder-placeholder.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'placeholder-o',
    appId: '1:placeholder:web:placeholder',
    messagingSenderId: 'placeholder',
    projectId: 'licenta-df25e',
    authDomain: 'licenta-df25e.firebaseapp.com',
    databaseURL: 'https://licenta-df25e-default-rtdb.firebaseio.com',
    storageBucket: 'licenta-df25e.firebasestorage.app',
    measurementId: 'G-placeholder',
  );

}