// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBCNPsAZShfin2AlM0_WshBacQHxhBo-o',
    appId: '1:132434659741:web:357e198174946e8fcb4774',
    messagingSenderId: '132434659741',
    projectId: 'licenta-df25e',
    authDomain: 'licenta-df25e.firebaseapp.com',
    databaseURL: 'https://licenta-df25e-default-rtdb.firebaseio.com',
    storageBucket: 'licenta-df25e.firebasestorage.app',
    measurementId: 'G-X8KST114MC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1bvV9JDa4XIAQ417b9ZB2wQbEMEzf8dk',
    appId: '1:132434659741:android:80fa32e9530640a3cb4774',
    messagingSenderId: '132434659741',
    projectId: 'licenta-df25e',
    databaseURL: 'https://licenta-df25e-default-rtdb.firebaseio.com',
    storageBucket: 'licenta-df25e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtaRBhOF7cy1VJ9M2JfU4UOZdHhVAMbKM',
    appId: '1:132434659741:ios:74ab2186def38f9fcb4774',
    messagingSenderId: '132434659741',
    projectId: 'licenta-df25e',
    databaseURL: 'https://licenta-df25e-default-rtdb.firebaseio.com',
    storageBucket: 'licenta-df25e.firebasestorage.app',
    iosClientId: '132434659741-7efknb0846o9j9vn1ocviqpgronsisfo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtaRBhOF7cy1VJ9M2JfU4UOZdHhVAMbKM',
    appId: '1:132434659741:ios:74ab2186def38f9fcb4774',
    messagingSenderId: '132434659741',
    projectId: 'licenta-df25e',
    databaseURL: 'https://licenta-df25e-default-rtdb.firebaseio.com',
    storageBucket: 'licenta-df25e.firebasestorage.app',
    iosClientId: '132434659741-7efknb0846o9j9vn1ocviqpgronsisfo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBCNPsAZShfin2AlM0_WshBacQHxhBo-o',
    appId: '1:132434659741:web:70a4719e53fda1cacb4774',
    messagingSenderId: '132434659741',
    projectId: 'licenta-df25e',
    authDomain: 'licenta-df25e.firebaseapp.com',
    databaseURL: 'https://licenta-df25e-default-rtdb.firebaseio.com',
    storageBucket: 'licenta-df25e.firebasestorage.app',
    measurementId: 'G-VQEFEEBWJY',
  );

}